
---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "manu@9148"

  tasks:
    - name: Login to docker registry
      shell: echo "{{ docker_registry_password }}" | docker login -u manu100 --password-stdin https://index.docker.io/v1/
    
    - name: pull image from docker hub
      shell: docker pull manu100/aws:tagname   

    - name: docker run
      shell: docker run --init   manu100/aws:tagname
