
---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "Seeusoon@1"

  tasks:
    - name: Login to docker registry
      shell: echo "{{ docker_registry_password }}" | docker login -u reehanruhullah --password-stdin https://index.docker.io/v1/
    
    - name: pull image from docker hub
      shell: docker pull reehanruhullah/dataphion_prac:tagname

    - name: docker run
      shell: docker run --init -d -p 80:5000 reehanruhullah/dataphion_prac:tagname