on:
  push:
      branches: [master]
  

jobs:
  build:
      runs-on: 
        -  self-hosted
        -  chris
      
      
      steps:
          
          - uses: actions/checkout@v4
          
          

          
          - name: Log in to Docker Hub
            run: |
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker image build -t manu100/aws:tagname .
              docker push manu100/aws:tagname
              
              
          - name: run ansible playbook
            if: github.ref == 'refs/heads/master'
            env:
              password: ${{ secrets.DOCKER_PASSWORD }}
            run: |
              ansible-playbook ansible.yml -i inventory.txt --extra-vars "password=$password"